# Generated by Django 3.0.7 on 2020-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200614_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=35)),
                ('phone', models.CharField(default='', max_length=15)),
                ('message', models.TextField(default='', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
